image_words<-c("imag" ,
               "pixel",
               "motion",
               "vision",
               "image elaborat",
               "computer vision" ,
               "image analys",
               "image process",
               "image data",
               "neural network")

tech_words <- c("vr",
                #"v\.r\.",
                "virtual real",
                "real.{0,10} time ",
                "remot.{0,10} control",
                "control.{0,10} unit",
                "control.{0,10} system",
                "visor" ,
                "sensor",
                "viewer" ,
                "simulator",
                "satellite navigator" ,
                "display" ,
                "gps",
                "camera",
                "driver",
                "eye" ,
                "cam" ,
                "helmet",
                "helmet.{0,10} cam.",
                "cam.{0,10} helmet",
                "foot cam",
                "foot-cam",
                "shoulder cam",
                "shoulder-cam")

motor_words <-c("motorsport",
                "sport",
                "racetrack",
                "bike",
                "ride",
                "vehicl.{0,10} race",
                "car.{0,10} rac",
                "boat.{0,10} rac",
                "rac[ei].{0,10} car",
                "rac[ei].{0,10} boat",
                "rac[ei].{0,10} rally",
                "rally.{0,10} race",
                "rally.{0,10} racing",
                "rac[ei].{0,10} kart.",
                "rac[ei].{0,10} kart.",
                "kart.{0,10} race",
                "kart.{0,10} racing",
                "moto.{0,10} sport.",
                "moto.{0,10} racing",
                "rac[ei].{0,10} moto",
                "race",
                "racing",
                "safe",
                "protect",
                "velocity",
                "moto.{0,10} speed",
                "speed.{0,10} moto",
                "ostacl",
                "barrie",
                "remote control")
