image_words<-c("imag" ,
               "imag.* elaborat",
               "computer vision" ,
               "imag.* analys",
               "imag.* process",
               "imag.* data",
               "neural.* network")

tech_words <- c("vr",
                #"v\.r\.",
                "virtual real" ,
                "visor" ,
                "viewer" ,
                "simulator",
                "satellite navigator" ,
                "display" ,
                "gps",
                "camera",
                "driver",
                "eye" ,
                "cam" ,
                "helmet",
                "helmet.* cam.",
                "cam.* helmet",
                "foot cam",
                "foot-cam",
                "shoulder cam",
                "shoulder-cam")

motor_words <-c("motorsport.",
                "vehicl.* race",
                "car.* rac",
                "boat.* rac",
                "race.* car",
                "racing* car",
                "race.* boat",
                "racing* boat",
                "race.* rally",
                "racing* rally",
                "rally.* race",
                "rally* racing.",
                "race.* kart.",
                "racing* kart.",
                "kart.* race",
                "kart* racing.",
                "moto.* sport.",
                "moto.* racing",
                "racing* moto",
                "race",
                "racing",
                "safe",
                "protect",
                "velocity",
                "moto.* speed",
                "speed* moto",
                "ostacl",
                "barrie",
                "remote control")
